config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :lists
  end

  scope "lists/:list_id", as: "list" do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    has_many :lists, dependent: :destroy
   
    def exists
        if self.name == nil
            false  
        else
            true
        end
    end
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :board
    has_many :tasks, dependent: :destroy
    def exists
        if self.name == nil
            false  
        else
            true
        end
    end
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :list
    def exists
        if self.name == nil
            false  
        else
            true
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  def index
    @boards = Board.all
  end

  def show
    #again implied- render :show
    
  end

  def new
    @board = Board.new
    render partial: "form"
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @board.update(board_params)
      redirect_to board_path(@board)
    else
      render :edit
    end

  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :update, :edit, :destroy]
  def index
    @lists = @board.lists
  end

  def show
  end

  def new
    @list = @board.lists.new
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to [@board, @list]
    else
      render :edit
    end
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to [@board, @list]
    else
      render :new
    end

  end

  def destroy
    @list.destroy
    redirect_to [@board, @list]
  end

  private
  

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController 
    before_action :set_list
    before_action :set_task, only: [:show, :update, :edit, :destroy]
    def index
      @tasks = @list.tasks
    end
  
    def show
    end
  
    def new
      @task = @list.tasks.new
    end
  
    def edit
    end
  
    def update
      if @task.update(task_params)
        redirect_to [@list, @task]
      else
        render :edit
      end
    end
  
    def create
      @task = @list.tasks.new(task_params)
  
      if @task.save
        redirect_to [@list, @task]
      else
        render :new
      end
  
    end
  
    def destroy
      @task.destroy
      redirect_to [@list, @task]
    end
  
    private

  
    def set_list
      @list = List.find(params[:list_id])
    end
  
    def set_task
      @task = Task.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:name)
    end 
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<h1><%= @board.id ? 'Edit Board' : 'Create Board' %></h1>
<hr />
<%= form_for @board do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name, required: true, autofocus: true %>
 <%= f.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>Boards</h1>
<%= render 'boards/form' %>

app/views/boards/index.html.erb
<h1>Click on a Board To Interact With Lists</h1>
<hr />
<%= link_to 'Create a new Board', new_board_path %>
<ul>
  <% @boards.each do |brd| %>
    <li><%= link_to brd.name, brd %></li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<h1>Boards</h1>

<h1>Click a Board To View Content</h1>
<%= link_to 'Create a new Board', new_board_path %>
<ul>
 <% @boards.each do |brd| %>
  <li><%= link_to brd.name, brd %></li>
 <% end %>
</ul>

app/views/boards/show.html.erb
<h1><%= @board.name %>-Board</h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Lists', board_lists_path(@board) %>
<br />
<%= link_to 'Edit Board', edit_board_path(@board) %>
<br />
<%= link_to 'Delete Board', @board, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create List' %></h1>
<hr />
<%= form_for [@board, @list] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<%= render 'lists/form' %>

app/views/lists/index.html.erb
<h1>Click on a List To Interact With Tasks</h1>
<hr />
<%= link_to 'Create a new List', new_board_list_path(@board) %>
<br />
<%= link_to 'Back to Boards', boards_path %>

<ul>
  <% @lists.each do |ls| %>
    <li><%= link_to ls.name, [@board, ls] %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= render 'lists/form' %>

app/views/lists/show.html.erb
<h1><%= @board.name %>-Board -- <%= @list.name %>-List</h1>
<hr />
<p><%= @list.name %></p>
<%= link_to 'View Tasks', list_tasks_path(@list) %>
<br />
<%= link_to 'Edit List', edit_board_list_path(@board, @list) %>
<br />
<%= link_to 'Delete List', [@board, @list], method: :delete %>
<br />
<%= link_to 'Back To Lists', board_lists_path(@board) %>

app/views/tasks/_form.html.erb
<h1><%= @task.id ? 'Edit Task' : 'Create Task' %></h1>
<hr />
<%= form_for [@list, @task] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'tasks/form' %>

app/views/tasks/index.html.erb
<h1>Click on a Task To Interact </h1>
<hr />
<%= link_to 'Create a new Task', new_list_task_path(@list) %>
<br />
<%= link_to 'Back To Boards', boards_path %>


<ul>
  <% @tasks.each do |ts| %>
    <li><%= link_to ts.name, [@list, ts] %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= render 'tasks/form' %>

app/views/tasks/show.html.erb
<h1><%= @list.name %>-List -- <%= @task.name %>-Task</h1>
<hr />
<p><%= @task.name %></p>
<br />
<%= link_to 'Edit Task', edit_list_task_path( @list, @task) %>
<br />
<%= link_to 'Delete Task', [@list, @task], method: :delete %>
<br />
<%= link_to 'Back To Tasks', list_tasks_path(@list) %>